kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "default.fullname" . }}
  labels:
    {{- include "default.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "default.fullname" . }}
    weight: 100
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow