apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: Configuration
    policy.open-cluster-management.io/controls: 'Post-Install'
    policy.open-cluster-management.io/description: Configure placement in hub cluster for Gitops.
    policy.open-cluster-management.io/standards: ''
  name: configure-placements
spec:
  disabled: false
  remediationAction: inform
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: configure-placements
        spec:
          pruneObjectBehavior: None
          remediationAction: inform
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: Placement
                metadata:
                  name: acm-placement
                  namespace: openshift-gitops
                spec:
                  clusterSets:
                    - acm
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: Placement
                metadata:
                  name: acm-placement
                  namespace: acm-policies
                spec:
                  clusterSets:
                    - acm
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: Placement
                metadata:
                  name: managed-placement
                  namespace: openshift-gitops
                spec:
                  clusterSets:
                    - managed
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: Placement
                metadata:
                  name: managed-placement
                  namespace: acm-policies
                spec:
                  clusterSets:
                    - managed
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: Placement
                metadata:
                  name: global-placement
                  namespace: acm-policies
                spec:
                  clusterSets:
                    - managed
                    - acm
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta2
                kind: ManagedClusterSetBinding
                metadata:
                  name: local-placement
                  namespace: openshift-gitops
                spec:
                  clusterSet: managed