apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-dr-managed-operators
  annotations:
    policy.open-cluster-management.io/categories: Operators
    policy.open-cluster-management.io/controls: DR-Persistence
    policy.open-cluster-management.io/description: Instala operadores para DR en los clusters administrados.
    policy.open-cluster-management.io/standards: ""
spec:
  disabled: false
  remediationAction: inform
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-oadp-operator
        spec:
          complianceType: musthave
          remediationAction: enforce
          severity: high
          operatorGroup:
            name: default
            targetNamespaces:
              - openshift-adp
          subscription:
            name: redhat-oadp-operator
            channel: stable-1.4
            source: redhat-operators
            namespace: openshift-adp
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-odr-operator
        spec:
          complianceType: musthave
          remediationAction: enforce
          severity: high
          subscription:
            name: odr-cluster-operator
            channel: stable-4.18
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-odf-operator
        spec:
          complianceType: musthave
          operatorGroup:
            name: openshift-storage
            targetNamespaces:
              - openshift-storage
          remediationAction: enforce
          severity: critical
          subscription:
            channel: stable-4.18
            name: odf-operator
            namespace: openshift-storage
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
          versions: null